# Generated by Django 4.1.5 on 2023-01-30 16:59

import api_requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_requests', '0004_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name', max_length=30, validators=[api_requests.models.Profile.validate_name]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(default='default.jpg', upload_to='Uploads/user/profile', validators=[api_requests.models.Profile.validate_image]),
        ),
    ]
